TITLE TO INPUT A STRING AND DISPLAY IT BACK

.MODEL SMALL
.STACK 100H
.DATA
	IN1 DB 'Enter any string: $'
	OUT1 DB 0DH,0AH,'Entered string is: $'
	STR1 DB 80 DUP('$')
.CODE
	MAIN PROC
		MOV AX,@DATA
		MOV DS,AX
		
		;PROMPT USER TO ENTER ANY STRING
		LEA DX,IN1
		MOV AH,09H
		INT 21H
		
		;INPUT THE STRING
		LEA DX,STR1
		MOV AH,0AH
		INT 21H
		
		;CHECK IF ENTER IS PRESSED
		CMP AL,0DH
		JZ DISPLAY
		
		;GREETING TO STRING
	DISPLAY:LEA DX,OUT1
		MOV AH,09H
		INT 21H
		
		;OUPUT OF ENTERED STRING
		LEA DX,STR1+2
		MOV AH,09H
		INT 21H
		
		MOV AH,4CH
		INT 21H
	MAIN ENDP
END MAIN
		