TITLE TO FIND THE LARGEST ELEMENT IN THE GIVEN 8-BIT DATA ARRAY

.MODEL SMALL
.STACK 100H
.DATA
	LIST DB 01H,06H,0AH,0CH,02H,03H
	RESULT DB 00H
.CODE
	MAIN PROC
		MOV AX,@DATA
		MOV DS,AX
		
		MOV CX,0006H ; COUNTER
		LEA SI,LIST
		
		MOV AL,[SI] ;ASSUMING 1ST DATA IN AL AS LARGEST
		DEC CX
		INC SI
		UP:CMP AL,[SI] ; COMPARE 1ST AND 2ND DATA
		JNC DOWN ; IF AL<2ND DATA
		MOV AL,[SI] ; MOVE 2ND DATA TO AL
		
		DOWN:INC SI
		LOOP UP
		MOV RESULT,AL ; AS AL CONTENTS LARGEST DATA
		
		MOV AH,4CH
		INT 21H
	MAIN ENDP
END MAIN
		