TITLE TO PRINT THE STRING IN REVERSE ORDER

.MODEL SMALL
.STACK 100H
.DATA
	STR1 DB 'gnirts','$'
	LENGTH DW 0006H
.CODE
	MAIN PROC
		MOV AX,@DATA
		MOV DS,AX
		
		MOV CX,LENGTH
		LEA SI,STR1
		
		;TO PUT ONE CHARACTER AT A TIME INTO STACK
		BACK:MOV BX,[SI]
		PUSH BX
		INC SI
		LOOP BACK
		
		;TO EXRACT ONE CHARACTER AT A TIME FROM STACK
		MOV CX,LENGTH
		REPEAT:POP DX
		MOV AH,02H ;FUNCTIONAL CALL TO PRINT A CHARACTER AT A TIME
		INT 21H
		LOOP REPEAT
		
		MOV AH,4CH
		INT 21H
	MAIN ENDP
END MAIN