TITLE TO TAKE A STRING INPUT AND PRINT THE STRING IN REVERSE ORDER

.MODEL SMALL
.STACK 100H
.DATA
	STR1 DB 'Ente any string ','$'
	LEN DB 30 DUP('$')
	STR2 DB 0DH,0AH,'The string in reverse order is ','$'
.CODE
	MAIN PROC
		MOV AX,@DATA
		MOV DS,AX
		
		;TO PROMPT THE USER TO ENTER ANY STRING
		LEA DX,STR1
		MOV AH,09H
		INT 21H
		
		;TO TAKE STRING INPUT FROM USER
		LEA DX,LEN
		MOV AH,0AH
		INT 21H
		
		;TO DISPLAY THE PROMPT OUTPUT
		LEA DX,STR2
		MOV AH,09H
		INT 21H
		
		;MOVE THE OFFSET VALUE OF LEN TO SI
		MOV SI,OFFSET LEN
		MOV CL,[SI+1] ;SINCE SI+1 STORES THE LENGTH OF THE STRING ENTERED
		MOV CH,00H
		
		;TO STORE THE CHARACTER ONE AT A TIME INTO STACK
		REPEAT:MOV BX,[SI+2]
		PUSH BX
		INC SI
		LOOP REPEAT
		
		;AGAIN RESET THE COUNTER TO POP THE CHARACTER ONE AT A TIME
		MOV SI,OFFSET LEN
		MOV CL,[SI+1]
		MOV CH,00H
		
		;EXRACT ONE CHARACTER AT A TIME
		NEXT:POP DX
		MOV AH,02H
		INT 21H
		LOOP NEXT
		
		MOV AH,4CH
		INT 21H
	MAIN ENDP
END MAIN