TITLE CONVERT LOWERCASE INTO UPPERCASE ALPHABETS

.MODEL SMALL
.STACK 100H
.DATA 
	IN1 DB 'Enter a character in lower case $'
	OUT1 DB 0DH,0AH,'The entered character in upper case is $'
.CODE
	MAIN PROC
		MOV AX,@DATA
		MOV DS,AX
		
		;PROMPT USER TO ENTER A CHARACTER
		LEA DX,IN1
		MOV AH,09H
		INT 21H
		
		;INPUT A CHARACTER AND CONVERT INTO UPPERCASE
		MOV AH,01H
		INT 21H
		SUB AL,20H ;TO CONVERT LOWER CASE INTO UPPER CASE
	 	MOV CL,AL
		
		;PROMPT UPPERCASE MESSAGE
		LEA DX,OUT1
		MOV AH,09H
		INT 21H
		
		;DISPLAY TS UPPERCASE
		MOV DL,CL
		MOV AH,02H
		INT 21H
		
		MOV AH,4CH
		INT 21H
	MAIN ENDP
END MAIN