TITLE TO TAKE A STRING FROM USER AND PRINT THE STRING IN UPPERCASE

.MODEL SMALL
.STACK 100H
.DATA
	STR1 DB 'Ente any string ','$'
	LEN DB 30 DUP('$')
	STR2 DB 0DH,0AH,'The entered string in uppercase is ','$'
.CODE
	MAIN PROC
		MOV AX,@DATA
		MOV DS,AX
		
		;TO PROMPT THE USER TO ENTER ANY STRING
		LEA DX,STR1
		MOV AH,09H
		INT 21H
		
		;TO TAKE STRING INPUT FROM USER
		LEA DX,LEN
		MOV AH,0AH
		INT 21H
		
		;TO DISPLAY THE PROMPT OUTPUT
		LEA DX,STR2
		MOV AH,09H
		INT 21H
		
		;MOVE THE OFFSET VALUE OF LEN TO SI
		MOV SI,OFFSET LEN
		MOV CL,[SI+1] ;SINCE SI+1 STORES THE LENGTH OF THE STRING ENTERED
		MOV CH,00H
		
		;TO STORE THE CHARACTER ONE AT A TIME INTO STACK
		REPEAT:MOV DL,[SI+2]
		SUB DL,20H
		MOV AH,02H
		INT 21H
		
		INC SI
		LOOP REPEAT
		
		MOV AH,4CH
		INT 21H
	MAIN ENDP
END MAIN